### ISSUE TITLE
[Bug] Tesserakt mod changes the value of world's gamerule

### ISSUE THREAD

**Issue by CrossVas** [Diamssword/TesseraktMod#3]
As the title stats, after installing this mod, and launch your world, two (?) gamerules change their values. Those gamerules are: 
doDaylightCycle - change from true to false;
doWeatherCycle - change from true to false. 

Also tried with no other mods, just forge and TesseraktMod - the same result. 

Step to reproduce: 
1. Start a new clean minecraft world;
2. Install TesseraktMod; 
3. After you installed TesseraktMod, launch your world.
4. Quit your world and enter again; 
5. Check the value of these two gamerules. 

Instance: 
MC version: 1.12.2
Mod version: tesserakt-2.0.1

After you enter for the second time into your world, you will see that level.dat get a backup.

Before TesseraktMod:
![2020-07-30](https://user-images.githubusercontent.com/25727222/88960859-cf290000-d2ac-11ea-82ac-018143f96a29.png)

After TesseraktMod:
![2020-07-30 (1)](https://user-images.githubusercontent.com/25727222/88960865-d0f2c380-d2ac-11ea-93c4-66606d3b8add.png)

**Comment by Diamssword** [comment]
Do they impact thé overworld? Rhodes gamerules are intended but should only affect a custom dimension I made, if it's not the case, I will look into it.
For now you can eventualy rollback to version 2.0 , it should fix it

**Comment by CrossVas** [comment]
Yes, Overworld is the dimension where time and weather are affected. 
Downgrading to 2.0 didn't solve the problem. Just checked and it seems like 1.3 doesn't affect anything.

**Comment by Diamssword** [comment]
Ok, It is fixed in the new version !
